"""Init

Revision ID: 4b7050c617c3
Revises: 233aa49bc990
Create Date: 2024-05-27 09:44:44.061706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b7050c617c3'
down_revision = '233aa49bc990'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
